app/thing/forms.py
from flask_wtf import FlaskForm
from wtforms import RadioField, SelectField, StringField
from wtforms.validators import InputRequired, Length, Optional


class ThingForm(FlaskForm):
    name = StringField(
        "Name",
        validators=[
            InputRequired(message="Enter a name"),
            Length(max=32, message="Name must be 32 characters or fewer"),
        ],
        description="Must be 32 characters or fewer.",
    )
    colour = RadioField(
        "Colour",
        validators=[InputRequired(message="Select a colour")],
        choices=[
            ("red", "Red"),
            ("green", "Green"),
            ("blue", "Blue"),
            ("yellow", "Yellow"),
            ("orange", "Orange"),
            ("purple", "Purple"),
            ("black", "Black"),
            ("white", "White"),
        ],
    )


class ThingFilterForm(FlaskForm):
    query = StringField("Search", validators=[Optional()])
    sort = SelectField(
        "Sort by",
        validators=[InputRequired()],
        choices=[
            ("created_at", "Most recent"),
            ("name", "Name"),
            ("colour", "Colour"),
            ("user_id", "Owner"),
        ],
        default="created_at",
    )
    per_page = SelectField(
        "Items per page",
        validators=[InputRequired()],
        choices=[(10, "10"), (20, "20"), (40, "40")],
        default=20,
    )
    colour = RadioField(
        "Colour",
        validators=[Optional()],
        choices=[
            ("", "All"),
            ("red", "Red"),
            ("green", "Green"),
            ("blue", "Blue"),
            ("yellow", "Yellow"),
            ("orange", "Orange"),
            ("purple", "Purple"),
            ("black", "Black"),
            ("white", "White"),
        ],
        default="",
    )


class ThingDeleteForm(FlaskForm):
    pass

app/thing/__init__.py
from flask import Blueprint

bp = Blueprint("thing", __name__, template_folder="../templates/thing", url_prefix="/things")

from app.thing import routes  # noqa: E402,F401

app/thing/routes.py
import csv
from datetime import datetime
from io import StringIO

import pytz
from flask import Response, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required
from werkzeug.exceptions import Forbidden

from app import db, limiter
from app.models import Thing
from app.thing import bp
from app.thing.forms import ThingDeleteForm, ThingFilterForm, ThingForm


@bp.route("/", methods=["GET", "POST"])
@login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def list():
    """Get a list of Things."""
    form = ThingFilterForm()

    colour = request.args.get("colour", type=str)
    page = request.args.get("page", type=int)
    per_page = request.args.get("per_page", type=int)
    search = request.args.get("query", type=str)
    sort_by = request.args.get("sort", type=str)

    query = Thing.query

    if search:
        query = query.filter(Thing.name.ilike(f"%{search}%"))
        form.query.data = search

    if colour:
        query = query.filter(Thing.colour == colour)
        form.colour.data = colour

    if sort_by and sort_by != "created_at":
        query = query.order_by(getattr(Thing, sort_by).asc(), Thing.created_at.desc())
        form.sort.data = sort_by
    else:
        query = query.order_by(Thing.created_at.desc())

    if per_page:
        form.per_page.data = str(per_page)

    things = query.paginate(page=page, per_page=per_page, max_per_page=40)

    return render_template("list_things.html", title="Things", things=things, form=form)


@bp.route("/new", methods=["GET", "POST"])
@login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def create():
    """Create a new Thing."""
    form = ThingForm()

    if form.validate_on_submit():
        new_thing = Thing(
            name=form.name.data.strip(),
            colour=form.colour.data,
            user_id=current_user.id,
        )
        db.session.add(new_thing)
        db.session.commit()
        flash(
            f"<a href='{url_for('thing.view', id=new_thing.id)}' class='alert-link'>{new_thing.name}</a> has been created.",
            "success",
        )
        return redirect(url_for("thing.list"))

    return render_template("create_thing.html", title="Create a new thing", form=form)


@bp.route("/<uuid:id>", methods=["GET"])
@login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def view(id):
    """Get a Thing with a specific ID."""
    thing = Thing.query.get_or_404(str(id))

    return render_template("view_thing.html", title=thing.name, thing=thing)


@bp.route("/<uuid:id>/edit", methods=["GET", "POST"])
@login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def edit(id):
    """Edit a Thing with a specific ID."""
    thing = Thing.query.get_or_404(str(id))
    if thing not in current_user.things:
        raise Forbidden()
    form = ThingForm()

    if form.validate_on_submit():
        thing.name = form.name.data.strip()
        thing.colour = form.colour.data
        thing.updated_at = pytz.utc.localize(datetime.utcnow())
        db.session.add(thing)
        db.session.commit()
        flash(
            f"Your changes to <a href='{url_for('thing.view', id=thing.id)}' class='alert-link'>{thing.name}</a> have been saved.",
            "success",
        )
        return redirect(url_for("thing.list"))
    elif request.method == "GET":
        form.name.data = thing.name
        form.colour.data = thing.colour

    return render_template(
        "update_thing.html",
        title=f"Edit {thing.name}",
        form=form,
        thing=thing,
    )


@bp.route("/<uuid:id>/delete", methods=["GET", "POST"])
@login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def delete(id):
    """Delete a Thing with a specific ID."""
    thing = Thing.query.get_or_404(str(id))
    if thing not in current_user.things:
        raise Forbidden()

    form = ThingDeleteForm()

    if request.method == "GET":
        return render_template(
            "delete_thing.html",
            title=f"Delete {thing.name}",
            form=form,
            thing=thing,
        )
    elif request.method == "POST":
        db.session.delete(thing)
        db.session.commit()
        flash(f"{thing.name} has been deleted.", "success")
        return redirect(url_for("thing.list"))


@bp.route("/download", methods=["GET"])
@login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def download():
    """Download a list of Things."""
    colour = request.args.get("colour", type=str)
    search = request.args.get("query", type=str)
    sort_by = request.args.get("sort", type=str)

    query = Thing.query

    if search:
        query = query.filter(Thing.name.ilike(f"%{search}%"))

    if colour:
        query = query.filter(Thing.colour == colour)

    if sort_by and sort_by != "created_at":
        query = query.order_by(getattr(Thing, sort_by).asc(), Thing.created_at.desc())
    else:
        query = query.order_by(Thing.created_at.desc())

    things = query.all()

    def generate():
        data = StringIO()
        w = csv.writer(data)

        # write header
        w.writerow(("ID", "NAME", "COLOUR", "USER_ID", "CREATED_AT", "UPDATED_AT"))
        yield data.getvalue()
        data.seek(0)
        data.truncate(0)

        # write each item
        for thing in things:
            w.writerow(
                (
                    thing.id,
                    thing.name,
                    thing.colour,
                    thing.user_id,
                    thing.created_at.isoformat(),
                    thing.updated_at.isoformat() if thing.updated_at else None,
                )
            )
            yield data.getvalue()
            data.seek(0)
            data.truncate(0)

    response = Response(generate(), mimetype="text/csv", status=200)
    response.headers.set("Content-Disposition", "attachment", filename="things.csv")
    return response

app/templates/thing/_thing_description.html
<dl class="row">
    <dt class="col-sm-3">Colour</dt>
    <dd class="col-sm-9">{{ thing.colour | title }}</dd>

    <dt class="col-sm-3">Created</dt>
    <dd class="col-sm-9">By <a href="{{ url_for('user.view', id=thing.user_id)}}">{{ thing.user.name }}</a> on {{ thing.created_at.strftime("%d/%m/%Y") }} at {{ thing.created_at.strftime("%H:%M:%S") }}</dd>

    <dt class="col-sm-3">Last updated</dt>
    <dd class="col-sm-9">{{ thing.updated_at.strftime("%d/%m/%Y %H:%M:%S") if thing.updated_at else "Never" }}</dd>
</dl>

app/templates/thing/_thing_form.html
<form action="" method="post" novalidate>
    {{ form.csrf_token }}
    <div class="mb-3">
        {{ form.name.label(class="form-label") }}
        {% if form.errors %}
            {% if form.name.errors %}
                {{ form.name(class="form-control is-invalid", type="text", spellcheck="true", aria_describedby="nameHelp") }}
                {% for error in form.name.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
            {% else %}
                {{ form.name(class="form-control is-valid", type="text", spellcheck="true", aria_describedby="nameHelp") }}
                <div class="valid-feedback">Looks good!</div>
            {% endif %}
        {% else %}
            {{ form.name(class="form-control", type="text", spellcheck="true", aria_describedby="nameHelp") }}
        {% endif %}
        <div id="nameHelp" class="form-text">{{ form.name.description }}</div>
    </div>
    <div class="mb-3">
        {{ form.colour.label(class="form-label") }}
        {% if form.errors %}
            {% if form.colour.errors %}
                {% for subfield in form.colour %}
                <div class="form-check mb-3">
                    {{ subfield(class="form-check-input is-invalid", type="radio") }}
                    {{ subfield.label(class="form-check-label") }}
                    {% for error in form.colour.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
                </div>
                {% endfor %}
            {% else %}
                {% for subfield in form.colour %}
                <div class="form-check">
                    {{ subfield(class="form-check-input is-valid", type="radio") }}
                    {{ subfield.label(class="form-check-label") }}
                </div>
                {% endfor %}
            {% endif %}
        {% else %}
            {% for subfield in form.colour %}
            <div class="form-check">
                {{ subfield(class="form-check-input", type="radio") }}
                {{ subfield.label(class="form-check-label") }}
            </div>
            {% endfor %}
        {% endif %}
    </div>
    <div class="d-grid gap-3 d-sm-block">
        <button class="btn btn-primary" type="submit"><i class="bi bi-save"></i> Save</button>
        <a class="btn btn-secondary" href="{{ request.referrer }}"><i class="bi bi-chevron-left"></i> Cancel</a>
    </div>
</form>

app/templates/thing/create_thing.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('thing.list') }}">Things</a></li>
                <li class="breadcrumb-item active" aria-current="page">New</li>
            </ol>
        </nav>
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        {% include '_thing_form.html' %}
    </div>
</div>
{% endblock %}

app/templates/thing/delete_thing.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('thing.list') }}">Things</a></li>
                <li class="breadcrumb-item"><a href="{{ url_for('thing.view', id=thing.id) }}">{{ thing.name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">Delete</li>
            </ol>
        </nav>
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        <p class="lead">Are you sure you want to delete {{ thing.name }}?</p>
        {% include '_thing_description.html' %}
        <form action="" method="post" novalidate>
            {{ form.csrf_token }}
            <div class="d-grid gap-3 d-sm-block">
                <button class="btn btn-danger" type="submit"><i class="bi bi-trash"></i> Yes, delete {{ thing.name }}</button>
                <a class="btn btn-secondary" href="{{ request.referrer }}"><i class="bi bi-chevron-left"></i> Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/thing/list_things.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col">
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="d-grid gap-3 mb-3">
            <a class="btn btn-primary btn-lg" href="{{ url_for('thing.create') }}"><i class="bi bi-plus-lg"></i> New thing</a>
        </div>
        <div class="card mb-3">           
            <div class="card-body">
                <form action="" method="get" novalidate>
                    <div class="mb-3">
                        {{ form.query.label(class="form-label") }}
                        {{ form.query(class="form-control", type="text") }}
                    </div>
                    <div class="mb-3">
                        {{ form.sort.label(class="form-label") }}
                        {{ form.sort(class="form-select") }}
                    </div>
                    <div class="mb-3">
                        {{ form.per_page.label(class="form-label")}}
                        {{ form.per_page(class="form-select") }}
                    </div>
                    <div class="mb-3">
                        {{ form.colour.label(class="form-label") }}
                        {% for subfield in form.colour %}
                            <div class="form-check">
                                {{ subfield(class="form-check-input", type="radio") }}
                                {{ subfield.label(class="form-check-label") }}
                            </div>
                        {% endfor %}
                    </div>
                    <div class="d-grid gap-3">
                        <button class="btn btn-secondary" type="submit"><i class="bi bi-filter"></i> Apply</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div class="col-md-9">
    {% if things %}
        <p class="mb-3">
            {% set x = things.per_page * things.prev_num + 1 if things.prev_num else 1 %}
            {% set y = things.per_page * things.page %}
            Showing <strong>{{ x }}</strong> to <strong>{{ y if y < things.total else things.total }}</strong> of <strong>{{ things.total }}</strong> things
            <a class="btn btn-secondary float-end" href="{{ url_for('thing.download') }}"><i class="bi bi-download"></i> Download {{ things.total }}</a>
        </p>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Colour</th>
                        <th scope="col">Owner</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for thing in things.items %}
                        <tr>
                            <th scope="row"><a href="{{ url_for('thing.view', id=thing.id) }}">{{ thing.name }}</a></th>
                            <td>{{ thing.colour | title }}</td>
                            <td><a href="{{ url_for('user.view', id=thing.user_id)}}">{{ thing.user.name }}</a></td>
                            <td>
                                {% if thing in current_user.things %}
                                <a href="{{ url_for('thing.edit', id=thing.id) }}"><i class="bi bi-pencil-square"></i> Edit</a><br>
                                <a href="{{ url_for('thing.delete', id=thing.id) }}" class="link-danger"><i class="bi bi-trash"></i> Delete</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% if things.pages > 1 %}
        <nav aria-label="Thing pages">
            <ul class="pagination">
                {% if things.has_prev %}
                <li class="page-item"><a class="page-link" href="{{ url_for('thing.list', page=things.prev_num, per_page=things.per_page) }}"><i class="bi bi-arrow-left"></i> Previous</a></li>
                {% endif %}
                {% for page in things.iter_pages(left_edge=1, left_current=2, right_current=3, right_edge=1) %}
                    {% if page %}
                        {% if page != things.page %}
                        <li class="page-item"><a class="page-link" href="{{ url_for('thing.list', page=page, per_page=things.per_page) }}">{{ page }}</a></li>
                        {% else %}
                        <li class="page-item active"><a class="page-link" href="{{ url_for('thing.list', page=page, per_page=things.per_page) }}">{{ page }}</a></li>
                        {% endif %}
                    {% else %}
                        <li class="page-item disabled"><a class="page-link" href="#">&ctdot;</a></li>
                    {% endif %}
                {% endfor %}
                {% if things.has_next %}
                <li class="page-item"><a class="page-link" href="{{ url_for('thing.list', page=things.next_num, per_page=things.per_page) }}">Next <i class="bi bi-arrow-right"></i></a></li>
                {% endif %}
            </ul>
        </nav>
        {% endif %}
    {% endif %}
    </div>
</div>
{% endblock %}

app/templates/thing/update_thing.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('thing.list') }}">Things</a></li>
                <li class="breadcrumb-item"><a href="{{ url_for('thing.view', id=thing.id) }}">{{ thing.name }}</a></li>
                <li class="breadcrumb-item active" aria-current="page">Edit</li>
            </ol>
        </nav>
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        {% include '_thing_form.html' %}
    </div>
</div>
{% endblock %}

app/templates/thing/view_thing.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{{ url_for('thing.list') }}">Things</a></li>
                <li class="breadcrumb-item active" aria-current="page">{{ title }}</li>
            </ol>
        </nav>
        {{ super() }}
        <h1 class="text-truncate">{{ title }}</h1>
        <hr>
        {% include '_thing_description.html' %}
        {% if thing in current_user.things %}
        <div class="d-grid gap-3 d-sm-block">
            <a class="btn btn-primary" href="{{ url_for('thing.edit', id=thing.id) }}"><i class="bi bi-pencil-square"></i> Edit</a>
            <a class="btn btn-danger" href="{{ url_for('thing.delete', id=thing.id) }}"><i class="bi bi-trash"></i> Delete</a>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}