app/user/forms.py
import pytz
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import BooleanField, PasswordField, SelectField, StringField
from wtforms.validators import Email, EqualTo, InputRequired, Length, Optional, ValidationError

from app.models import User


class SignupForm(FlaskForm):
    tz_tuples = []
    for tz in pytz.common_timezones:
        tz_tuples.append((tz, tz.replace("_", " ")))

    name = StringField("Full name", validators=[InputRequired("Enter your full name")])

    email_address = StringField(
        "Email address",
        validators=[
            InputRequired(message="Enter your email address"),
            Email(granular_message=True, check_deliverability=True),
            Length(max=256, message="Email address must be 256 characters or fewer"),
        ],
        description="We'll never share your email with anyone else.",
    )
    password = PasswordField(
        "Create a password",
        validators=[
            InputRequired(message="Enter a password"),
            Length(min=8, max=72, message="Password must be between 8 and 72 characters"),
        ],
        description="Must be between 8 and 72 characters.",
    )
    confirm_password = PasswordField(
        "Confirm password",
        validators=[
            InputRequired(message="Confirm your password"),
            EqualTo("password", message="Passwords must match."),
        ],
    )
    timezone = SelectField(
        "Timezone",
        validators=[InputRequired(message="Select a timezone")],
        choices=tz_tuples,
        default="Europe/London",
    )

    def validate_email_address(self, email_address):
        user = User.query.filter_by(email_address=email_address.data).first()
        if user is not None:
            raise ValidationError("Email address is already in use, please log in")


class LoginForm(FlaskForm):
    email_address = StringField(
        "Email address",
        validators=[
            InputRequired(message="Enter an email address"),
            Email(granular_message=True, check_deliverability=True),
            Length(max=256, message="Email address must be 256 characters or fewer"),
        ],
    )
    password = PasswordField(
        "Password",
        validators=[
            InputRequired(message="Enter a password"),
            Length(min=8, max=72, message="Password must be between 8 and 72 characters"),
        ],
        description="Must be between 8 and 72 characters.",
    )
    remember_me = BooleanField("Remember me", validators=[Optional()])


class UserForm(FlaskForm):
    tz_tuples = []
    for tz in pytz.common_timezones:
        tz_tuples.append((tz, tz.replace("_", " ")))

    name = StringField("Full name", validators=[InputRequired("Enter your full name")])

    email_address = StringField(
        "Email address",
        validators=[
            InputRequired(message="Enter your email address"),
            Email(granular_message=True, check_deliverability=True),
            Length(max=256, message="Email address must be 256 characters or fewer"),
        ],
        description="We'll never share your email with anyone else.",
    )

    timezone = SelectField(
        "Timezone",
        validators=[InputRequired(message="Select a timezone")],
        choices=tz_tuples,
        default="Europe/London",
    )

    def validate_email_address(self, email_address):
        if email_address.data != current_user.email_address:
            user = User.query.filter_by(email_address=email_address.data).first()
            if user is not None:
                raise ValidationError("Email address is already in use")


class UserDeleteForm(FlaskForm):
    pass

app/user/__init__.py
from flask import Blueprint

bp = Blueprint("user", __name__, template_folder="../templates/user")

from app.user import routes  # noqa: E402,F401

app/user/routes.py
from datetime import datetime

import pytz
from flask import current_app, flash, redirect, render_template, request, url_for
from flask_login import current_user, fresh_login_required, login_required, login_user, logout_user
from werkzeug.exceptions import Forbidden
from werkzeug.urls import url_parse

from app import db, limiter
from app.models import User
from app.user import bp
from app.user.forms import LoginForm, SignupForm, UserDeleteForm, UserForm


@bp.route("/signup", methods=["GET", "POST"])
def signup():
    if current_user.is_authenticated:
        return redirect(url_for("entry.weekly"))
    form = SignupForm()
    if form.validate_on_submit():
        user = User(
            name=form.name.data,
            email_address=form.email_address.data,
            password=form.password.data,
            timezone=form.timezone.data,
        )
        user.login_at = pytz.utc.localize(datetime.utcnow())
        db.session.add(user)
        db.session.commit()
        current_app.logger.info(f"User {user.id} created")
        login_user(user)
        current_app.logger.info(f"User {current_user.id} logged in")
        flash(f"Welcome {current_user.name}", "success")
        return redirect(url_for("thing.list"))
    return render_template("sign_up_form.html", title="Sign up", form=form)


@bp.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email_address=form.email_address.data).first()
        if user is None or not user.check_password(form.password.data):
            current_app.logger.warning("Failed login attempt")
            flash("Invalid email address or password.", "danger")
            return redirect(url_for("user.login"))
        login_user(user, remember=form.remember_me.data)
        user.login_at = pytz.utc.localize(datetime.utcnow())
        db.session.add(user)
        db.session.commit()
        current_app.logger.info(f"User {current_user.id} logged in")
        next_page = request.args.get("next")
        if not next_page or url_parse(next_page).netloc != "":
            next_page = url_for("thing.list")
        flash(f"{current_user.name} logged in.", "success")
        return redirect(next_page)
    elif request.method == "GET" and current_user.is_authenticated:
        form.email_address.data = current_user.name
    return render_template("log_in_form.html", title="Log in", form=form)


@bp.route("/logout")
def logout():
    current_app.logger.info(f"User {current_user.id} logged out")
    name = current_user.name
    logout_user()
    flash(f"{name} logged out.", "success")
    return redirect(url_for("main.index"))


@bp.route("/users/<uuid:id>", methods=["GET"])
@login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def view(id):
    """Get a User with a specific ID."""
    user = User.query.get_or_404(str(id))

    return render_template("view_user.html", title=user.name, user=user)


@bp.route("/users/<uuid:id>/edit", methods=["GET", "POST"])
@fresh_login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def edit(id):
    """Edit a User with a specific ID."""
    if str(id) != current_user.id:
        raise Forbidden()

    form = UserForm()
    if form.validate_on_submit():
        current_user.email_address = form.email_address.data.lower().strip()
        current_user.name = form.name.data.strip()
        current_user.timezone = form.timezone.data
        current_user.updated_at = pytz.utc.localize(datetime.utcnow())
        db.session.add(current_user)
        db.session.commit()
        flash("Account changes have been saved.", "success")
        current_app.logger.info(f"User {current_user.id} updated account")
        return redirect(url_for("user.view", id=current_user.id))
    elif request.method == "GET":
        form.name.data = current_user.name
        form.email_address.data = current_user.email_address
        form.timezone.data = current_user.timezone
    return render_template("update_user.html", title="Edit user", form=form)


@bp.route("/users/<uuid:id>/delete", methods=["GET", "POST"])
@fresh_login_required
@limiter.limit("2 per second", key_func=lambda: current_user.id)
def delete(id):
    """Delete a User with a specific ID."""
    if str(id) != current_user.id:
        raise Forbidden()

    form = UserDeleteForm()

    if request.method == "GET":
        return render_template("delete_user.html", title="Delete account", form=form, user=current_user)
    elif request.method == "POST":
        current_app.logger.info(f"User {current_user.id} deleted account")
        db.session.delete(current_user)
        db.session.commit()
        flash(
            "Your account and all personal information has been permanently deleted.",
            "success",
        )
        return redirect(url_for("main.index"))

app/templates/user/_user_description.html
<dl class="row">
    {% if current_user.email_address == user.email_address %}
    <dt class="col-sm-3">Email address</dt>
    <dd class="col-sm-9">{{ user.email_address }}</dd>
    {% endif %}
    <dt class="col-sm-3">Timezone</dt>
    <dd class="col-sm-9">{{ user.timezone }}</dd>

    <dt class="col-sm-3">Created</dt>
    <dd class="col-sm-9">{{ user.created_at.strftime("%d/%m/%Y %H:%M:%S") }}</dd>

    <dt class="col-sm-3">Last log in</dt>
    <dd class="col-sm-9">{{ user.login_at.strftime("%d/%m/%Y %H:%M:%S") }}</dd>

    <dt class="col-sm-3">Last updated</dt>
    <dd class="col-sm-9">{{ user.updated_at.strftime("%d/%m/%Y %H:%M:%S") if user.updated_at else "Never" }}</dd>
</dl>

app/templates/user/delete_user.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        <p class="lead">Are you sure you want to delete {{ user.name }}?</p>
        {% include '_user_description.html' %}
        <form action="" method="post" novalidate>
            {{ form.csrf_token }}
            <div class="d-grid gap-3 d-sm-block">
                <button class="btn btn-danger" type="submit"><i class="bi bi-trash"></i> Yes, delete {{ user.name }}</button>
                <a class="btn btn-secondary" href="{{ request.referrer }}"><i class="bi bi-chevron-left"></i> Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/user/log_in_form.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {{ super() }}
        <h1 class="text-truncate">{{ title }}</h1>
        <hr>
        <form action="" method="post" class="mb-3" novalidate>
            {{ form.csrf_token }}
            <div class="mb-3">
                {{ form.email_address.label(class="form-label") }}
                {% if form.errors %}
                    {% if form.email_address.errors %}
                        {{ form.email_address(class="form-control is-invalid", type="email", spellcheck="false", autocomplete="email") }}
                        {% for error in form.email_address.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
                    {% else %}
                        {{ form.email_address(class="form-control is-valid", type="email", spellcheck="false", autocomplete="email") }}
                        <div class="valid-feedback">Looks good!</div>
                    {% endif %}
                {% else %}
                    {{ form.email_address(class="form-control", type="email", spellcheck="false", autocomplete="email") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.password.label(class="form-label") }}
                {% if form.errors %}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid", aria_describedby="passwordHelp") }}
                        {% for error in form.password.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
                    {% else %}
                        {{ form.password(class="form-control is-valid", aria_describedby="passwordHelp") }}
                        <div class="valid-feedback">Looks good!</div>
                    {% endif %}
                {% else %}
                    {{ form.password(class="form-control", aria_describedby="passwordHelp") }}
                {% endif %}
                <div id="passwordHelp" class="form-text">{{ form.password.description }}</div>
            </div>
            <div class="mb-3">
                <div class="form-check">
                    {{ form.remember_me(class="form-check-input", type="checkbox") }}
                    {{ form.remember_me.label(class="form-check-label") }}
                </div>
            </div>
            <div class="d-grid gap-3 d-md-block">
                <button class="btn btn-primary" type="submit"><i class="bi bi-box-arrow-in-right"></i> Log in</button>
                <a class="btn btn-secondary" href="{{ request.referrer }}"><i class="bi bi-chevron-left"></i> Cancel</a>
            </div>         
        </form>
    </div>
</div>
{% endblock %}

app/templates/user/sign_up_form.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {{ super() }}
        <h1 class="text-truncate">{{ title }}</h1>
        <hr>
        <form action="" method="post" novalidate>
            {{ form.csrf_token }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {% if form.errors %}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control is-invalid", type="text", spellcheck="false", autocomplete="name") }}
                        {% for error in form.name.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
                    {% else %}
                        {{ form.name(class="form-control is-valid", type="text", spellcheck="false", autocomplete="name") }}
                        <div class="valid-feedback">Looks good!</div>
                    {% endif %}
                {% else %}
                    {{ form.name(class="form-control", type="text", spellcheck="false", autocomplete="name") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.email_address.label(class="form-label") }}
                {% if form.errors %}
                    {% if form.email_address.errors %}
                        {{ form.email_address(class="form-control is-invalid", type="email", spellcheck="false", autocomplete="email", aria_describedby="emailHelp") }}
                        {% for error in form.email_address.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
                    {% else %}
                        {{ form.email_address(class="form-control is-valid", type="email", spellcheck="false", autocomplete="email", aria_describedby="emailHelp") }}
                        <div class="valid-feedback">Looks good!</div>
                    {% endif %}
                {% else %}
                    {{ form.email_address(class="form-control", type="email", spellcheck="false", autocomplete="email", aria_describedby="emailHelp") }}
                {% endif %}
                <div id="emailHelp" class="form-text">{{ form.email_address.description }}</div>
            </div>
            <div class="mb-3">
                {{ form.password.label(class="form-label") }}
                {% if form.errors %}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control is-invalid", aria_describedby="passwordHelp") }}
                        {% for error in form.password.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
                    {% else %}
                        {{ form.password(class="form-control is-valid", aria_describedby="passwordHelp") }}
                        <div class="valid-feedback">Looks good!</div>
                    {% endif %}
                {% else %}
                    {{ form.password(class="form-control", aria_describedby="passwordHelp") }}
                {% endif %}
                <div id="passwordHelp" class="form-text">{{ form.password.description }}</div>
            </div>
            <div class="mb-3">
                {{ form.confirm_password.label(class="form-label") }}
                {% if form.errors %}
                    {% if form.confirm_password.errors %}
                        {{ form.confirm_password(class="form-control is-invalid") }}
                        {% for error in form.confirm_password.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
                    {% else %}
                        {{ form.confirm_password(class="form-control is-valid") }}
                        <div class="valid-feedback">Looks good!</div>
                    {% endif %}
                {% else %}
                    {{ form.confirm_password(class="form-control") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.timezone.label(class="form-label") }}
                {% if form.errors %}
                    {% if form.timezone.errors %}
                        {{ form.timezone(class="form-select is-invalid") }}
                        {% for error in form.timezone.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
                    {% else %}
                        {{ form.timezone(class="form-select is-valid") }}
                        <div class="valid-feedback">Looks good!</div>
                    {% endif %}
                {% else %}
                    {{ form.timezone(class="form-select") }}
                {% endif %}
            </div>
            <div class="d-grid gap-3 d-md-block">
                <button class="btn btn-primary" type="submit"><i class="bi bi-person-plus-fill"></i> Sign up</button>
                <a class="btn btn-secondary" href="{{ request.referrer }}"><i class="bi bi-chevron-left"></i> Cancel</a>
            </div> 
        </form>
    </div>
</div>
{% endblock %}

app/templates/user/update_user.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {{ super() }}
        <h1>{{title}}</h1>
        <hr>
        <form action="" method="post" novalidate>
            {{ form.csrf_token }}
            <div class="mb-3">
                {{ form.name.label(class="form-label") }}
                {% if form.errors %}
                    {% if form.name.errors %}
                        {{ form.name(class="form-control is-invalid", type="text", spellcheck="false", autocomplete="name") }}
                        {% for error in form.name.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
                    {% else %}
                        {{ form.name(class="form-control is-valid", type="text", spellcheck="false", autocomplete="name") }}
                        <div class="valid-feedback">Looks good!</div>
                    {% endif %}
                {% else %}
                    {{ form.name(class="form-control", type="text", spellcheck="false", autocomplete="name") }}
                {% endif %}
            </div>
            <div class="mb-3">
                {{ form.email_address.label(class="form-label") }}
                {% if form.errors %}
                    {% if form.email_address.errors %}
                        {{ form.email_address(class="form-control is-invalid", type="email", spellcheck="false", autocomplete="email", aria_describedby="emailHelp") }}
                        {% for error in form.email_address.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
                    {% else %}
                        {{ form.email_address(class="form-control is-valid", type="email", spellcheck="false", autocomplete="email", aria_describedby="emailHelp") }}
                        <div class="valid-feedback">Looks good!</div>
                    {% endif %}
                {% else %}
                    {{ form.email_address(class="form-control", type="email", spellcheck="false", autocomplete="email", aria_describedby="emailHelp") }}
                {% endif %}
                <div id="emailHelp" class="form-text">{{ form.email_address.description }}</div>
            </div>
            <div class="mb-3">
                {{ form.timezone.label(class="form-label") }}
                {% if form.errors %}
                    {% if form.timezone.errors %}
                        {{ form.timezone(class="form-select is-invalid") }}
                        {% for error in form.timezone.errors %}<div class="invalid-feedback">{{error}}</div>{% endfor %}
                    {% else %}
                        {{ form.timezone(class="form-select is-valid") }}
                        <div class="valid-feedback">Looks good!</div>
                    {% endif %}
                {% else %}
                    {{ form.timezone(class="form-select") }}
                {% endif %}
            </div>
            <div class="d-grid gap-3 d-md-block">
                <button class="btn btn-primary" type="submit"><i class="bi bi-save"></i> Save</button>
                <a class="btn btn-secondary" href="{{ request.referrer }}"><i class="bi bi-chevron-left"></i> Cancel</a>
            </div>
        </form>
    </div>
</div>
{% endblock %}

app/templates/user/view_user.html
{% extends "base.html" %}
{% block content %}
<div class="row">
    <div class="col-md-8">
        {{ super() }}
        <h1 class="text-truncate">{{ title }}</h1>
        <hr>
        {% include '_user_description.html' %}
        {% if current_user.id == user.id %}
        <div class="d-grid gap-3 d-sm-block mb-3">
            <a class="btn btn-primary" href="{{ url_for('user.edit', id=current_user.id) }}"><i class="bi bi-pencil-square"></i> Edit</a>
            <a class="btn btn-danger" href="{{ url_for('user.delete', id=current_user.id) }}"><i class="bi bi-trash"></i> Delete</a>
        </div>
        {% endif %}
        {% if user.things %}
        <h2>Things</h2>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col">Name</th>
                        <th scope="col">Colour</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for thing in user.things %}
                        <tr>
                            <th scope="row"><a href="{{ url_for('thing.view', id=thing.id) }}">{{ thing.name }}</a></th>
                            <td>{{ thing.colour | title }}</td>
                            <td>
                                {% if thing in current_user.things %}
                                <a href="{{ url_for('thing.edit', id=thing.id) }}"><i class="bi bi-pencil-square"></i> Edit</a><br>
                                <a href="{{ url_for('thing.delete', id=thing.id) }}" class="link-danger"><i class="bi bi-trash"></i> Delete</a>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
        {% else %}
        <p class="lead">0 things</p>
        {% endif %}
    </div>
</div>
{% endblock %}